### ISSUE TITLE
Unnecessary Autoloading bug

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#492]
In v 0.8.8 (and older) there is this one bug that if you  load one model, unload it and manually load another, sometimes if you try to chat the app will still try to autoload the model you just unloaded and get stuck until you kill the app.

**Comment by Vali-98** [comment]
Let me know if the latest beta fixed this:
https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.9-beta6

**Comment by GameOverFlowChart** [comment]
> Let me know if the latest beta fixed this: https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.9-beta6

Both it and the b version crash with a model missing toast appearing as in #509

**Comment by Vali-98** [comment]
This crash is likely fixed here
https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.9-beta7

**Comment by GameOverFlowChart** [comment]
> This crash is likely fixed here https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.9-beta7

Still crashes saying model missing. Maybe deleting app data would fix but I wouldn't want to lose other data, a version which deletes the model list at start might work. I'm not sure if I can downgrade to save my data, Android usually doesn't allow installing older versions without uninstalling.

**Comment by Vali-98** [comment]
The unloading portion is likely resolved since beta6, and most crashes have been resolved in latest.
